# Generated by Django 5.1 on 2024-08-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cats",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("pets", models.IntegerField(default=0)),
            ],
        ),
    ]
